# Dockerfile para Piper con Python 3.10
FROM python:3.10

WORKDIR /usr/src/app

COPY requirements.txt .

# Instalar dependencias, incluyendo piper-tts
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8001"]
